

services:

  db:
    image: mysql/mysql-server:5.7
    env_file:
      - ./conf/.env
    ports:
      - "33006:3306"
    volumes:
      - dbdata_baseproyecto:/var/lib/mysql  # Volumen para persistir datos de MySQL
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql  # Montar el archivo SQL para restauración automática
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - baseproyecto_net

  backend: &backend
    build: 
      dockerfile: Dockerfile
      context: . 
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/code
    ports:
      - "8081:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./conf/.env
    networks:
      - baseproyecto_net

networks:
  baseproyecto_net:

volumes:
  dbdata_baseproyecto: