# Generated by Django 4.1.1 on 2024-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryserp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecategory', models.CharField(blank=True, db_column='nameCategory', max_length=45, null=True)),
                ('parentcategoryid', models.IntegerField(blank=True, db_column='parentCategoryId', null=True)),
                ('childrencategoryid', models.IntegerField(blank=True, db_column='childrenCategoryId', null=True)),
                ('iderp', models.IntegerField(blank=True, db_column='idERP', null=True)),
            ],
            options={
                'db_table': 'categorysERP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastid', models.IntegerField(blank=True, db_column='lastID', null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('prefixed', models.CharField(blank=True, max_length=4, null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryID', null=True)),
            ],
            options={
                'db_table': 'productConfig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=45, null=True)),
                ('nameproduct', models.CharField(blank=True, db_column='nameProduct', max_length=250, null=True)),
                ('prefixed', models.CharField(blank=True, max_length=500, null=True)),
                ('brands', models.CharField(blank=True, max_length=100, null=True)),
                ('codebar', models.CharField(blank=True, max_length=45, null=True)),
                ('codebar2', models.CharField(blank=True, max_length=45, null=True)),
                ('codebar3', models.CharField(blank=True, max_length=45, null=True)),
                ('iderp', models.CharField(blank=True, db_column='idERP', max_length=45, null=True)),
                ('codsupplier', models.CharField(blank=True, db_column='codSupplier', max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('lastcost', models.IntegerField(blank=True, db_column='lastCost', null=True)),
                ('latestreplenishment', models.DateTimeField(blank=True, db_column='latestReplenishment', null=True)),
                ('lastprice', models.IntegerField(blank=True, db_column='lastPrice', null=True)),
                ('typeprice', models.IntegerField(blank=True, db_column='typePrice', null=True)),
                ('currentstock', models.IntegerField(blank=True, db_column='currentStock', null=True)),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True)),
                ('imgthumbs', models.CharField(blank=True, db_column='imgThumbs', max_length=500, null=True)),
                ('idmelimain', models.CharField(blank=True, db_column='IDMELIMAIN', max_length=100, null=True)),
                ('idproduct', models.IntegerField(blank=True, db_column='idProduct', null=True)),
                ('meliprice_s1', models.IntegerField(blank=True, db_column='meliPrice_s1', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productscost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('purchasedate', models.DateField(blank=True, db_column='purchaseDate', null=True)),
                ('idsupplier', models.IntegerField(blank=True, db_column='idSupplier', null=True)),
            ],
            options={
                'db_table': 'productsCost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productsprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('offerprice', models.IntegerField(blank=True, db_column='offerPrice', null=True)),
                ('manualprice', models.IntegerField(blank=True, db_column='manualPrice', null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('effectivedate', models.DateField(blank=True, db_column='effectiveDate', null=True)),
                ('effectivedatetime', models.DateTimeField(blank=True, db_column='effectiveDateTime', null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('idplist', models.IntegerField(blank=True, db_column='idPlist', null=True)),
                ('idvariantplist', models.IntegerField(blank=True, db_column='idVariantPlist', null=True)),
            ],
            options={
                'db_table': 'productsPrices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=45, null=True)),
                ('suppliername', models.CharField(blank=True, db_column='supplierName', max_length=100, null=True)),
                ('typedoc', models.IntegerField(blank=True, db_column='typeDoc', null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=45, null=True)),
                ('dateadd', models.DateField(blank=True, db_column='dateAdd', null=True)),
                ('dateproccess', models.DateField(blank=True, db_column='dateProccess', null=True)),
                ('idpurchase', models.CharField(blank=True, db_column='idPurchase', max_length=100, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('urljson', models.CharField(blank=True, db_column='urlJson', max_length=500, null=True)),
                ('urlimg', models.CharField(blank=True, db_column='urlImg', max_length=500, null=True)),
                ('printstatus', models.IntegerField(blank=True, db_column='printStatus', null=True)),
                ('dateprint', models.DateField(blank=True, db_column='datePrint', null=True)),
                ('iddocument', models.CharField(blank=True, db_column='idDocument', max_length=45, null=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectoroffice',
            fields=[
                ('idsectoroffice', models.AutoField(db_column='idSectorOffice', primary_key=True, serialize=False)),
                ('idoffice', models.IntegerField(db_column='idOffice')),
                ('iduserresponsible', models.IntegerField(blank=True, db_column='idUserResponsible', null=True)),
                ('zone', models.CharField(blank=True, max_length=5, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('namesector', models.CharField(blank=True, db_column='nameSector', max_length=45, null=True)),
                ('picturearea', models.CharField(blank=True, db_column='pictureArea', max_length=1000, null=True)),
                ('diagramarea', models.CharField(blank=True, db_column='diagramArea', max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('pdfbarcode', models.CharField(blank=True, db_column='pdfBarcode', max_length=500, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('namedescriptive', models.CharField(blank=True, db_column='nameDescriptive', max_length=100, null=True)),
            ],
            options={
                'db_table': 'sectorOffice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesupplier', models.CharField(blank=True, db_column='nameSupplier', max_length=45, null=True)),
                ('rutsupplier', models.CharField(blank=True, db_column='rutSupplier', max_length=45, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uniqueproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproduct', models.IntegerField(blank=True, db_column='idProduct', null=True)),
                ('superid', models.CharField(blank=True, db_column='superID', max_length=45, null=True)),
                ('correlative', models.IntegerField(blank=True, null=True)),
                ('printlabel', models.IntegerField(blank=True, db_column='printLabel', null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('soldvalue', models.IntegerField(blank=True, db_column='soldValue', null=True)),
                ('datelastinventory', models.DateTimeField(blank=True, db_column='dateLastInventory', null=True)),
                ('observation', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('typedocincome', models.IntegerField(blank=True, db_column='typeDocIncome', null=True)),
                ('ndocincome', models.IntegerField(blank=True, db_column='nDocIncome', null=True)),
                ('typedocout', models.IntegerField(blank=True, db_column='typeDocOut', null=True)),
                ('ndocout', models.IntegerField(blank=True, db_column='nDocOut', null=True)),
                ('dateadd', models.DateTimeField(blank=True, db_column='dateAdd', null=True)),
                ('iddocumentincome', models.IntegerField(blank=True, db_column='idDocumentIncome', null=True)),
                ('ncompany', models.IntegerField(blank=True, db_column='nCompany', null=True)),
                ('locationname', models.CharField(blank=True, db_column='locationName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'uniqueProducts',
                'managed': False,
            },
        ),
    ]
