# Generated by Django 4.1.1 on 2024-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(default='40emmett90', max_length=100)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VENTAS', 'Ventas'), ('BODEGA', 'Bodega')], default='VENTAS', max_length=10)),
            ],
        ),
    ]
