# Generated by Django 4.1.1 on 2025-02-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=100)),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='idProduct', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_prices', to='core.products')),
            ],
            options={
                'db_table': 'marketplace_prices',
                'unique_together': {('product', 'marketplace')},
            },
        ),
    ]
