# Generated by Django 4.1.1 on 2024-10-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idExternal', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('country', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('isVirtual', models.BooleanField(default=False)),
                ('costCenter', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('hrefExternal', models.URLField(blank=True, null=True)),
                ('urlPhoto', models.URLField(blank=True, null=True)),
                ('emailStore', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('idoffice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodega', to='core.sectoroffice')),
            ],
        ),
    ]
