# Generated by Django 4.1.1 on 2024-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='hrefExternal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='idoffice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='urlPhoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
