# Generated by Django 4.1.1 on 2024-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bodega_city_alter_bodega_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('total_unit_value', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
