# Generated by Django 4.1.1 on 2024-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usuario_clave_remove_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='40emmett90', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENTAS', 'Ventas'), ('BODEGA', 'Bodega'), ('SADMIN', 'SuperAdmin')], default='VENTAS', max_length=10),
        ),
    ]
