# Generated by Django 4.1.1 on 2024-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
