# Generated by Django 4.1.1 on 2024-11-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
