# Generated by Django 4.1.1 on 2024-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uniquecodebar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nameproduct',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
