# Generated by Django 4.1.1 on 2024-11-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_products_uniquecodebar_alter_products_nameproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
