# Generated by Django 4.1.1 on 2024-11-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
