# Generated by Django 4.1.1 on 2024-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=6, unique=True)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
