# Generated by Django 4.1.1 on 2024-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dynamickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='alto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='largo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='profundidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
