# Generated by Django 4.1.1 on 2024-11-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_products_alto_products_largo_products_peso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
    ]
