# Generated by Django 4.1.1 on 2024-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='subtotal_with_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
