# Generated by Django 4.1.1 on 2024-11-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_purchase_subtotal_with_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryserp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productscost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productsprices',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectoroffice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uniqueproducts',
            options={},
        ),
    ]
