# Generated by Django 4.1.1 on 2024-11-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_categoryserp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uniqueproducts',
            name='idproduct',
        ),
        migrations.AddField(
            model_name='uniqueproducts',
            name='product',
            field=models.ForeignKey(blank=True, db_column='idProduct', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_products', to='core.products'),
        ),
        migrations.AlterField(
            model_name='uniqueproducts',
            name='ncompany',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
