# Generated by Django 4.1.1 on 2024-11-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_brand_category_remove_uniqueproducts_idproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='uniqueproducts',
            name='product',
            field=models.ForeignKey(db_column='idProduct', on_delete=django.db.models.deletion.CASCADE, related_name='unique_products', to='core.products'),
        ),
    ]
