# Generated by Django 4.1.1 on 2024-11-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_uniqueproducts_product'),
        ('core', '0023_delete_brand_delete_category_and_more'),
    ]

    operations = [
    ]
