# Generated by Django 4.1.1 on 2024-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueproducts',
            name='printlabel',
            field=models.CharField(blank=True, db_column='printLabel', max_length=255, null=True),
        ),
    ]
