# Generated by Django 4.1.1 on 2024-12-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_uniqueproducts_printlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueproducts',
            name='superid',
            field=models.CharField(blank=True, db_column='superID', db_index=True, max_length=45, null=True),
        ),
    ]
