# Generated by Django 4.1.1 on 2025-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_products_sku_alter_uniqueproducts_superid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueproducts',
            name='reingreso_document_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
