# Generated by Django 4.1.1 on 2025-01-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_uniqueproducts_reingreso_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.IntegerField(choices=[(0, 'Boleta'), (1, 'Factura')])),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('dispatched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('dispatched_quantity', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProductSuperID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superid', models.CharField(max_length=100, unique=True)),
                ('dispatched', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superids', to='core.invoiceproduct')),
            ],
        ),
    ]
